# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================
spring:
  cloud:
    stream:
      default:
        consumer:
          concurrency: 3
      rabbit:
        bindings:
          megabeaconChannel:
            consumer:
              maxConcurrency: 5
              prefetch: 3
      bindings:
        megabeaconChannel:
          binder: megabeaconBinder
          group: megabeacon.wfevents.solrfeed.test
          destination: arccl.wfevents.solr
      binders:
        megabeaconBinder:
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest 
                cloud:
                    bus:
                    enabled: true
                    refresh:
                      enabled: true
                        
                #ssl:
                #  enabled: true

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================
#property name changes to be done
application:
  mail:
    solrRecipients: sudheer.akurathi@viacomcontractor.com;ganapati.hegde@viacomcontractor.com;Surya.Sai@viacomcontractor.com
    queueRecipients: sudheer.akurathi@viacomcontractor.com;ganapati.hegde@viacomcontractor.com;Surya.Sai@viacomcontractor.com
    sender: ganapati.hegde@viacomcontractor.com
    subject: 'SOLR Alert, Site : Wf Events Process - DEV - '
  solr:
    host: http://localhost:8983/solr
    collection: wf4
  contentRefresh:
    delay: 0 0/3 * * * ?
    schedulerOn: false
    batchSize: 10000
    query: timestamp:[2021-06-19T00:00:00.000Z TO 2021-06-25T23:45:00.000Z]&nocache=%d
